"use client";

import { motion } from "framer-motion";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { AnimateOnScroll } from "@/components/ui/AnimateOnScroll";
import { CTABand } from "@/components/sections/CTABand";
import { Badge } from "@/components/ui/Badge";
import {
  Lock, Fingerprint, KeyRound, ShieldAlert, Database, CheckCircle
} from "lucide-react";

const features = [
  {
    icon: Lock,
    title: "SSL/TLS Encryption",
    desc: "All data transmitted between your device and GIO4X servers is encrypted using industry-standard 256-bit SSL/TLS encryption. This ensures that your personal information, login credentials, and trading data cannot be intercepted or read by unauthorized parties.",
    badge: "256-bit",
  },
  {
    icon: Fingerprint,
    title: "Two-Factor Authentication (2FA)",
    desc: "Add an extra layer of security to your account with two-factor authentication. In addition to your password, you will need to verify your identity using a one-time code sent to your mobile device or generated by an authenticator app every time you log in.",
    badge: "Recommended",
  },
  {
    icon: KeyRound,
    title: "Secure Login & Session Management",
    desc: "Our login system detects suspicious activity such as logins from unusual locations or devices. Sessions automatically expire after periods of inactivity. All passwords are stored using advanced cryptographic hashing and are never stored in plain text.",
    badge: "Always On",
  },
  {
    icon: ShieldAlert,
    title: "Anti-Fraud Systems",
    desc: "GIO4X employs real-time fraud detection systems that monitor account activity for unusual patterns. Automated alerts are triggered for suspicious transactions, unauthorized access attempts, and other potential security threats. Our dedicated security team investigates all flagged events.",
    badge: "Real-time",
  },
  {
    icon: Database,
    title: "Data Protection & Privacy",
    desc: "Your personal data is protected in accordance with the highest data protection standards. We implement strict access controls, regular security audits, data encryption at rest, and secure backup procedures. Your information is never shared with third parties without your explicit consent.",
    badge: "GDPR Ready",
  },
];

const tips = [
  "Use a strong, unique password and change it regularly",
  "Enable two-factor authentication on your account",
  "Never share your login credentials with anyone",
  "Always log out when using shared or public devices",
  "Be wary of phishing emails claiming to be from GIO4X",
  "Keep your operating system and browser up to date",
  "Only download our apps from official sources",
  "Contact support immediately if you notice suspicious activity",
];

export default function OnlineSecurityPage() {
  return (
    <>
      {/* Hero */}
      <section className="pt-56 pb-44 relative overflow-hidden">
        {/* Hero Visual Elements */}
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-20 left-1/4 w-64 h-64 bg-[#29ABE2]/5 rounded-full blur-3xl animate-[float_8s_ease-in-out_infinite]" />
          <div className="absolute bottom-10 right-1/4 w-48 h-48 bg-[#1B3A6B]/10 rounded-full blur-3xl animate-[float_10s_ease-in-out_infinite_2s]" />
          <div className="absolute top-1/2 right-10 w-32 h-32 bg-[#C9A84C]/5 rounded-full blur-2xl animate-[float_12s_ease-in-out_infinite_4s]" />
        </div>
        <div className="max-site text-center relative z-10">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <Badge variant="sky">Protection</Badge>
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="text-[var(--text-h1)] font-bold mt-4 mb-4">
            Online <span className="gradient-text">Security</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="text-[var(--color-text-secondary)] text-lg max-w-2xl mx-auto">
            Your account security is our priority. We use enterprise-grade security infrastructure to protect your data and trading activity.
          </motion.p>
        </div>
      </section>

      {/* Features */}
      <section className="section-padding bg-[var(--color-surface)]">
        <div className="max-site">
          <SectionHeading eyebrow="Infrastructure" title="Multi-Layer Security" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {features.map((feature, i) => (
              <AnimateOnScroll key={feature.title} delay={i * 0.1}>
                <div className="glass-panel p-6 h-full">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#1B3A6B] to-[#29ABE2] flex items-center justify-center shrink-0">
                      <feature.icon className="w-5 h-5 text-white" />
                    </div>
                    <h3 className="font-bold text-sm">{feature.title}</h3>
                    <Badge variant="navy" className="ml-auto">{feature.badge}</Badge>
                  </div>
                  <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">{feature.desc}</p>
                </div>
              </AnimateOnScroll>
            ))}
          </div>
        </div>
      </section>

      {/* Security Tips */}
      <section className="section-padding">
        <div className="max-site max-w-3xl">
          <SectionHeading eyebrow="Best Practices" title="Stay Safe Online" subtitle="Follow these tips to keep your GIO4X account secure." />
          <AnimateOnScroll>
            <div className="glass-panel p-8">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {tips.map((tip) => (
                  <div key={tip} className="flex gap-3 items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                    <p className="text-sm text-[var(--color-text-secondary)]">{tip}</p>
                  </div>
                ))}
              </div>
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      {/* Report Section */}
      <section className="pb-16">
        <div className="max-site max-w-3xl">
          <AnimateOnScroll>
            <div className="glass-panel p-6 border-amber-500/30 text-center">
              <ShieldAlert className="w-10 h-10 text-amber-400 mx-auto mb-3" />
              <h3 className="font-bold mb-2">Report a Security Concern</h3>
              <p className="text-sm text-[var(--color-text-secondary)] mb-4">
                If you suspect unauthorized access to your account or have received a suspicious communication claiming to be from GIO4X, contact our security team immediately.
              </p>
              <p className="text-[#29ABE2] font-semibold text-sm">security@gio4x.com</p>
            </div>
          </AnimateOnScroll>
        </div>
      </section>

      <CTABand />
    </>
  );
}
